feat(UIKIT-1150) Переезд на vite + react-router
kaluga-astral/vite-boilerplate pull request #1
Opened 2024-01-17 12:50 UTC by Ofigelov

2024-01-18 16:07 UTC, AndTem requested changes

2024-01-18 16:07 UTC, AndTem commented on pages/_app.tsx
> +import { useRoutes } from 'react-router-dom';
Здесь для роутера должна быть инверсия через shared

2024-01-18 16:07 UTC, AndTem commented on shared/ui/components/RouterServiceAdapter/RouterServiceAdapter.tsx
> +export const RouterServiceAdapter = () => {
Adapter ли? Может просто Router компонент?

2024-01-18 16:07 UTC, AndTem commented on shared/ui/components/RouterServiceAdapter/RouterServiceAdapter.tsx
> +      navigate: (path, _params) =>
```suggestion
      navigate: (path, params) =>
```

2024-01-18 16:10 UTC, AndTem commented on package.json
> +    "dev": "vite dev",
У меня не запускается, просто зависает старт. Ты пробовал запускать?

2024-01-18 16:12 UTC, AndTem commented on package.json
> +    "dev": "vite dev",
Ошибка при запуске:
<img width="1206" alt="Снимок экрана 2024-01-18 в 19 11 58" src="https://github.com/kaluga-astral/vite-boilerplate/assets/23665108/5e8e5f08-fbd2-4b8f-a8f3-418c4f353f3c">

2024-01-19 05:06 UTC, Ofigelov commented on pages/index.html
> +<!doctype html>
`index.html ` это отправная точка для vite, без него не выйдет, и перенести его не получится.
а public должен находиться там же где и index.html

2024-01-19 05:08 UTC, Ofigelov commented on shared/images/disconnection.svg
vite ругается на ассеты, которые мы пытаемся хранить в public, говорит что они должны быть где-нибудь кроме public

2024-01-19 05:10 UTC, Ofigelov commented on shared/ui/icons/index.ts
> -export { ReactComponent as PlayIcon } from 'public/icons/play-icon.svg';
не было использования, и импорт из public

2024-01-19 05:16 UTC, Ofigelov commented on shared/ui/components/RouterServiceAdapter/RouterServiceAdapter.tsx
> +export const RouterServiceAdapter = () => {
Я так и знал что ты спросишь это, но я не знаю как иначе назвать этот компонент. Его задача адапитаровать реактовый роутер, к апишному. Это адаптер не как паттерн, а адаптер по поведению. Или может как учитель...

2024-01-19 05:19 UTC, Ofigelov commented on vite.config.mts
> +export default defineConfig({
используем, просто его инициализация в самом приложении сборщик ничего с ним не делает.

2024-01-19 05:23 UTC, Ofigelov commented on vite.config.mts
> +dotenv.config();
он из коробки работает в рантайме, а при запуске сборки у нас нет доступа к ним.

2024-01-19 05:29 UTC, Ofigelov commented on vite.config.mts
> +const alias: AliasOptions = Object.entries(compilerOptions.paths).reduce(
незнаю. заменю.

2024-01-19 05:31 UTC, Ofigelov commented on vite.config.mts
> +import legacy from '@vitejs/plugin-legacy';
Ну, я подумал, что если это бойлерплейт, то он должен быть универсальным, и подходить под большинство случаев, тем более если эта универсальность включается оч просто. Мне не принципиально, уберу.

2024-01-19 05:41 UTC, Ofigelov commented on shared/services/MonitoringErrorService/MonitoringErrorService.ts
> +      release: '1.0.0',
а было как?) было только магия некста, который что-то делал с сентри, и всё

2024-01-19 05:42 UTC, Ofigelov commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> +  public navigate: NavigateHandler = (path, params) => {
replace делать по запросу. а пуш, это же просто навигация на нужный адрес?

2024-01-19 05:57 UTC, Ofigelov commented on pages/_app.tsx
> +import { useRoutes } from 'react-router-dom';
это же единственное место, где нам требуется использовать этот хук. и он специфичен именно для react-router в тех же tanstack и nextjs его нет, заменять будет нечем. т.к. по архитектуре application слой самый грязный, предлагаю оставить так.

2024-01-19 05:59 UTC, Ofigelov commented on package.json
> +    "dev": "vite dev",
у меня запускается без проблем. попробуй node_modules переустановить?

2024-01-19 07:15 UTC, AndTem commented on vite.config.mts
> +dotenv.config();
Оставь комментарий в коде

2024-01-19 07:23 UTC, AndTem commented on shared/images/disconnection.svg
Может в корне проекта сделать директорию static?

2024-01-19 07:24 UTC, AndTem commented on shared/services/ConfigService/ConfigService.ts
> +  sentryDsn: string;
У тебя сервис называется MonitoringService, а тут sentry упоминается

2024-01-19 07:25 UTC, AndTem commented on shared/services/MonitoringErrorService/MonitoringErrorService.ts
> +      release: '1.0.0',
Ок.
release тоже должен из параметра браться. Для каждоый сборки должен быть уникальный release

2024-01-19 07:26 UTC, AndTem commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> + * чтобы адаптировать реакт роутер к апи версии,
Какой версии?

2024-01-19 07:26 UTC, AndTem commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> +  public navigate: NavigateHandler = (path, params) => {
Не понял тебя.
Ходить по истории можно всего двумя способами: push и replace.
Как мне тут выбрать механизм?

2024-01-19 07:34 UTC, AndTem commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> +   * метод установки параметров необходимых для корректной работы
Очень бесполезный коммент. Пересмотри доклад: https://www.youtube.com/watch?v=DfAKTC7ZKdY&ab_channel=AstralFrontend

2024-01-19 07:36 UTC, AndTem commented on shared/ui/icons/index.ts
> -export { ReactComponent as PlayIcon } from 'public/icons/play-icon.svg';
Это демонстрация генерации из svg компонента (svgr)

2024-01-19 07:37 UTC, AndTem commented on package.json
> +    "dev": "vite dev",
пробовал

2024-01-19 11:11 UTC, Ofigelov commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> + * чтобы адаптировать реакт роутер к апи версии,
тут я под версиями я подразумеваю - реализации, версия для реакта, версия для апи, версия для мока

2024-01-19 12:44 UTC, Ofigelov commented on shared/ui/icons/index.ts
> -export { ReactComponent as PlayIcon } from 'public/icons/play-icon.svg';
Как обсудили в тг, добавил в shared/icons

2024-01-19 12:55 UTC, Ofigelov commented on vite.config.mts
> +export default defineConfig({
в общем это требует отдельного исследования, наш сентри немного отличается от того, что сказано в описании этого плагина. Предлагаю оставить пока как есть, с инициализацией в рантайме, и создать отдельную задачу на внедрение сентри в билде.

2024-01-19 12:56 UTC, Ofigelov commented on shared/images/disconnection.svg
как обсудили в тг, создал папку shared/icons. shared/images уже есть

2024-01-19 13:11 UTC, AndTem commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> + * чтобы адаптировать реакт роутер к апи версии,
Так и напиши

2024-01-19 13:11 UTC, Ofigelov commented on shared/services/RouterService/AdaptableRouterService/AdaptableRouterService.ts
> +  public navigate: NavigateHandler = (path, params) => {
я к тому, что это сервис на быструю руку, с минимально необходимым функционалом, по подобию того, как это сделано у нас в кэдо. 
Для меня пуш, это просто навигация по сайту. Для этого и есть метод navigate.
Для replace, я расширил типизацию опций передаваемых в navigate метод

2024-01-19 13:45 UTC, merged